### ISSUE TITLE
Doesn't look like TTL is honored

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/Announce#10]
I have created an announcement with a TTL of 60 (seconds).  The announcement started showing, but it continued to show even after the 60 seconds expired.  I marked the announcement as dismiss-able, but never dismissed it.

**Comment by dregad** [comment]
I'm afraid John never fully implemented this feature...

**Comment by vboctor** [comment]
Until it is added, I suggest hiding the field that allows user to enter TTL and just default it to 0.  This is to avoid confusion.

**Comment by dregad** [comment]
Easier to implement it than to hide the field ;-)

Let me know if it doesn't work
