### ISSUE TITLE
Dismiss announcement doesn't work

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/Announce#11]
Clicking the dismiss X doesn't have any effect and no javascript console errors.

**Comment by dregad** [comment]
Can you please check your settings for *$g_display_errors*, specifically the value for _E_USER_DEPRECATED_ ?

I noticed that the plugin still relies on deprecated *db_query_bound()* function, which triggers a warning in the dismissal script; when I tested, I had it on `inline`, so the request executed successfully, but when it's set to `halt` the ajax fails.

I'll fix the deprecated call, and add logging in case of failure.
