### ISSUE TITLE
Growing dismissed table

### ISSUE THREAD

**Issue by atrol** [mantisbt-plugins/Announce#17]
I expect a quite fast growing `dismissed` table if a lot of users are using the system.

To prevent this, at least related entries should be deleted when deleting an announcement.

**Comment by dregad** [comment]
@atrol can you please test if PR #20 addresses the issue ?

**Comment by atrol** [comment]
Tested a bit PR #20 
Looks good, tried upgrade (cleanup) and deleting announcements.

**Comment by dregad** [comment]
Thanks for testing !
