### ISSUE TITLE
Franch translation and Change color of announce message

### ISSUE THREAD

**Issue by Celemo** [mantisbt-plugins/Announce#33]
Can you ?

- [ ] Add French translation (Give me a file to translate and I will translate it)
- [ ] Add a box to change color of announce message

Thanks,
Celemo

**Comment by dregad** [comment]
For the translation: you will find the latest English strings in 
https://github.com/mantisbt-plugins/Announce/blob/master/lang/strings_english.txt
Please submit a pull request with the translated file (-> `strings_french.txt`)

As for the the color change, I would suggest that you just modify the _announcement_ class in 
https://github.com/mantisbt-plugins/Announce/blob/master/files/announce.css
I don't think it's worth the effort to develop a config setting and GUI for that, but if you're willing to provide a pull request to implement this feature, I will gladly accept it.
