### ISSUE TITLE
Cannot Dimiss

### ISSUE THREAD

**Issue by decstewartje** [mantisbt-plugins/Announce#41]
Clicking the "X" does not dismiss the announcement, though the dismiss flag is checked.
No errors produced.

**Comment by decstewartje** [comment]
Looks like an error calling the REST api... Headers produce 405 errors at:

`http://webserver/mantisbt/api/rest/index.php/plugins/Announce/dismiss/1`

**Comment by dregad** [comment]
It works for me... AJAX returns 200 and announcements are dismissed successfully.

Feel free to reopen the issue with additional information including steps to reproduce the problem.

**Comment by cc08** [comment]
I confirm this problem in next configuration: debian-buster/4.19.0-8-amd64,  nginx/1.14.2,  php-fpm7.3.8,  PostgreSQL 12.2.  
Clicking the "X" dismiss the announcement on current page, but when you go to any other page, the announce appears again.
Perhaps this is due to the use of postgresql, since the tables look like "mantis_mantis_announce_context_mantis" (doubled prefix) ?

**Comment by dregad** [comment]
@cc08 check for messages in your browser's console. What is the status of the `dismiss` ajax POST request ? It should be 200. You can also check that a record corresponding to the dismissed announcement's context for the current user was successfully inserted/updated in the plugin's _dismissed_ table.

As for the table's name, it should be `mantis_plugin_announce_XXX_table` with MantisBT default values, but maybe you changed the table pre/suffixes in your configuration ? That should not impact the plugin's behavior though.

**Comment by cc08** [comment]
I see request "POST /api/rest/index.php/plugins/Announce/dismiss/1 HTTP/1.1" and answer 302. 
In table "mantis_mantis_announce_dismissed_mantis" record not appears, respectively.
Prefix and suffix of tables, set by default - "mantis", I did not change them.
Mantis version - 2.23.0. 
Now it seems to me that the nginx config is to blame.
