### ISSUE TITLE
The old announcments sometimes will show

### ISSUE THREAD

**Issue by jl33** [mantisbt-plugins/Announce#47]
Sometimes old announcments will showing again,which those announcments were exceeded the "time of live".
I use the newest version 2.4.0 of Ammounce with Mantisbt 2.17.0.

**Comment by jl33** [comment]
Thank you for your answer.
Indeed, I have to dismiss it, and no longer see the announcment again. But,what does the "Time to Live" mean?
I thought the "Time to Live" means that an announcment will automatically disappear after the time has elapsed,even the user do not dismiss it.

**Comment by dregad** [comment]
> I thought the "Time to Live" means that an announcment will automatically disappear after the time has elapsed,even the user do not dismiss it.

Yes that's exactly what it is. Note that the plugin makes no difference between a "manual" dismissal, and the "automatic" one (i.e. after timeout).

**Comment by jl33** [comment]
Finally,I test and find out the key point. 
The "Time to Live" is only useful for announcments that not check the "Dismissable" checkbox.
So there is no bug, just a misunderstand.
Thank you!

**Comment by dregad** [comment]
> The "Time to Live" is only useful for announcments that not check the "Dismissable" checkbox.

That's not fully correct. Time to live can also be used with Dismissable announcements; in that case the user can either dismiss the message by clicking the X, or wait until the timeout expires.

Anyway, thanks for the feedback.

**Comment by jl33** [comment]
> Time to live can also be used with Dismissable announcements; in that case the user can either dismiss the message by clicking the X, or wait until the timeout expires.

I found "Time to Live" actually means while I open and stop at a specific page, and wait for that time pass, then the announcement will disappear.
But, if I open and go to another page before the time ended, the announcement will appear on every new page. This is what I saw.
And more, unless wait for an announcement disappear ---- wait for time ended on one page ---- I will always see the announcement, never disappear.

**Comment by dregad** [comment]
You're absolutely right. It works with a timer on the page, which is starts when the page loads. 

Maintaining the timer across several pages within the user's session would be quite complicated, especially considering that as you reach another page, another announcement might be displayed (if there is more than one active, it is selected randomly).
