### ISSUE TITLE
Time to Live and Dismissable are not working properly

### ISSUE THREAD

**Issue by nacholettieri** [mantisbt-plugins/Announce#48]
I've been creating announcements with TTL and after that time they haven't disappeared. Maybe I'm not using the functionality well. I was hoping that the user would stop seeing the messages after that time. Is that right?

On the other hand, when I click on the cross at the top right to discard the messages, nothing happens.

**Comment by dregad** [comment]
Sounds like the JavaScript code is not executing. Are there any error in the browser's console ?

**Comment by dregad** [comment]
Closing due to lack of feedback. Feel free to reopen with additional information.
