### ISSUE TITLE
Dutch language file

### ISSUE THREAD

**Issue by sander16091992** [mantisbt-plugins/Announce#49]
I've made an translation to Dutch feel free to add it to the git resources
[strings_dutch.txt](https://github.com/mantisbt-plugins/Announce/files/2848189/strings_dutch.txt)

**Comment by dregad** [comment]
Thanks for your contribution !

If possible, please, next time send a pull request instead of attaching the file :wink: 

Incidentally, this should also avoid encoding issues, as your text file was in ISO-8859 instead of UTF-8 (causing problems with some accented chars).

**Comment by dregad** [comment]
[v2.4.1](https://github.com/mantisbt-plugins/Announce/releases/tag/v2.4.1) is out, including your translations.
