### ISSUE TITLE
Text processing for display destroy A tag content

### ISSUE THREAD

**Issue by jerome-dl** [mantisbt-plugins/Announce#54]
Hi,
It is allowed (and that's nice!) to enter some HTML tags in the text (and even in the title) of the announce we want to have displayed.
However, trying to add a `<a>` tag, the result is modified and, especially, the text between `<a>` and `</a>` tags is **lost**.
_E.g.:_
`<a href="https://***/workflow-mantis.png" target="_blank">Workflow</a>`
becomes
`<a href="https://***/workflow-mantis.png">https://***/workflow-mantis.png</a>`

I know the _target_ attribute is not officially supported by HTML5 (however widely used, still) so I may understand it remains filtered.

Kind regards,
Jérôme

**Comment by dregad** [comment]
@jerome-dl the text processing is done via standard MantisBT API calls. 

In this specific case, the plugin calls *string_display_links()*, which relies on the [MantisCoreFormatting plugin](https://github.com/mantisbt/mantisbt/blob/master-2.24/plugins/MantisCoreFormatting/MantisCoreFormatting.php#L84). this process removes anchor tags for security reasons (preventing potential XSS attacks), using the [string_strip_hrefs() function](https://github.com/mantisbt/mantisbt/blob/master/core/string_api.php#L574).
